---
# tasks file for lxc

- name: install epel-release
  yum: name=epel-release state=present

- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - lxc
    - lxc-templates
    - lxc-doc
    - lxc-libs
    - rsync
    - debootstrap
    - bridge-utils

- name: add bridge config
  template:
    src: ifcfg-virbr0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-virbr0
    owner: root
    group: root
    mode: 0644
  notify: restart network

- name: enable ipv4 ip forward
  lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_forward = 1"
  notify: load sysctl

- meta: flush_handlers

- name: start and enable lxc
  service: name=lxc state=started enabled=yes
