Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |v|
    v.memory = "2048"
    #v.gui = true
    # change network adapter type and promiscuous mode
    #v.customize ['modifyvm', :id, '--nictype1', 'Am79C973']
    #v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
    #v.customize ['modifyvm', :id, '--nictype2', 'Am79C973']
    #v.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.sudo = true
  end
end
